COMMENT: 'Training on ZInd'
TAG: 'zind_all'
SEED: 123
MODEL:
  NAME: 'Bi_Layout'
  TYPE: 'occlusion'
  ARGS: [ {
    'decoder_name': 'Share_Feature_Guidance_Module',
    'win_size': 16,
    'rpe': 'lr_parameter_mirror',
    'dropout': 0.0,
    'depth': 8,
    'output_name': 'Bi_Layout',
    'output_number': 2,
    'feature_channel': 512,
    'height_compression_scale': 16,
    'use_same_head': False,
    'share_TF': True,
    'two_conv_out': False,
  } ]
TRAIN:
  DEVICE: 'cuda:0'
  SCRATCH: False
  DETERMINISTIC: True
  CRITERION:
    DEPTH:
      WEIGHT: 0.9
    NEW_DEPTH:
      WEIGHT: 0.9
    RATIO:
      WEIGHT: 0.1
    GRAD:
      WEIGHT: 0.1
      WEIGHTS: [ 1.0, 1.0 ]
    NEW_GRAD:
      WEIGHT: 0.1
      WEIGHTS: [ 1.0, 1.0 ]
  BASE_LR:
    1e-4
  RESUME_LAST: False
  OPTIMIZER:
    NAME: 'adam'
  EPOCHS: 200
DATA:
  DATASET: 'zind'
  # DIR: '/media/public_dataset/ZInD/data'  # your ZInD dataset path
  DIR: '/ssd2/yuju/lgtnet_dataset/ZInD'
  TYPE: 'both' # raw, visible, both (using both will be for bi-layout version)
  SIMPLICITY: 'both'  # simple, complex, both
  PRIMARY: 'both'  # primary, secondary, both
  BATCH_SIZE: 12
  NUM_WORKERS: 12
  FOR_TEST_INDEX: None
  AUG:
    FLIP: True
    STRETCH: True
    ROTATE: True
    GAMMA: True
EVAL:
  EVAL_GT_MISMATCH: True  # need to be True if you want to evaluate on ZInD dataset
  # OPENING: True # the model will have opening output if True
AMP_OPT_LEVEL: 'O0'
