COMMENT: 'Training on ZInd'
TAG: 'zind_all_on_zind_simple'
SEED: 123
MODEL:
  NAME: 'Bi_Layout'
  TYPE: 'occlusion'
  ARGS: [ {
    'decoder_name': 'Share_Feature_Guidance_Module',
    'win_size': 16,
    'rpe': 'lr_parameter_mirror',
    'dropout': 0.0,
    'depth': 8,
    'output_name': 'Bi_Layout',
    'output_number': 2,
    'use_same_head': False,
    'share_TF': True,
  } ]
  DEFINITION_MISMATCH: True # for correct oracle test
TRAIN:
  DEVICE: 'cuda:2'
  SCRATCH: False
  DETERMINISTIC: True
  CRITERION:
    DEPTH:
      WEIGHT: 0.9
    NEW_DEPTH:
      WEIGHT: 0.9
    RATIO:
      WEIGHT: 0.1
    GRAD:
      WEIGHT: 0.1
      WEIGHTS: [ 1.0, 1.0 ]
    NEW_GRAD:
      WEIGHT: 0.1
      WEIGHTS: [ 1.0, 1.0 ]
    # OPENING:
    #   WEIGHT: 0.5
  BASE_LR:
    1e-4
  RESUME_LAST: False
  OPTIMIZER:
    NAME: 'adam'
  EPOCHS: 200
DATA:
  DATASET: 'zind'
  # DIR: 'src/dataset/zind'
  DIR: '/media/public_dataset/ZInD/data'
  TYPE: 'both' # raw, visible, both -> both will be for two-head
  SIMPLICITY: 'both'  # simple, complex, both
  PRIMARY: 'both'  # primary, secondary, both
  BATCH_SIZE: 12
  NUM_WORKERS: 12
  FOR_TEST_INDEX: None
  AUG:
    FLIP: True
    STRETCH: True
    ROTATE: True
    GAMMA: True
AMP_OPT_LEVEL: 'O0'
